//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BadIceCreamFinal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BadIceCreamFinal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream gameMusic {
            get {
                return ResourceManager.GetStream("gameMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bricks&gt;
        ///	&lt;!--middle square--&gt;
        ///	&lt;brick type=&quot;error&quot; x=&quot;342&quot; y=&quot;246&quot; width=&quot;38&quot; height=&quot;41&quot; colour=&quot;CadetBlue&quot; /&gt;
        ///	&lt;brick type=&quot;error&quot; x=&quot;380&quot; y=&quot;246&quot; width=&quot;38&quot; height=&quot;41&quot; colour=&quot;CadetBlue&quot; /&gt;
        ///	&lt;brick type=&quot;error&quot; x=&quot;304&quot; y=&quot;246&quot; width=&quot;38&quot; height=&quot;41&quot; colour=&quot;CadetBlue&quot; /&gt;
        ///	&lt;brick type=&quot;error&quot; x=&quot;380&quot; y=&quot;287&quot; width=&quot;38&quot; height=&quot;41&quot; colour=&quot;CadetBlue&quot; /&gt;
        ///	&lt;brick type=&quot;error&quot; x=&quot;342&quot; y=&quot;287&quot; width=&quot;38&quot; height=&quot;41&quot; colour=&quot;CadetBlue&quot; /&gt;
        ///	&lt;brick type=&quot;error&quot; x=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lvl1 {
            get {
                return ResourceManager.GetString("lvl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bricks&gt;
        ///	&lt;brick x=&quot;44&quot; y=&quot;46&quot; width=&quot;28&quot; height=&quot;32&quot; colour=&quot;MediumSlateBlue&quot; /&gt;
        ///	&lt;brick x=&quot;44&quot; y=&quot;88&quot; width=&quot;28&quot; height=&quot;32&quot; colour=&quot;MediumSlateBlue&quot; /&gt;
        ///	&lt;brick x=&quot;44&quot; y=&quot;414&quot; width=&quot;28&quot; height=&quot;32&quot; colour=&quot;MediumSlateBlue&quot; /&gt;
        ///	&lt;brick x=&quot;44&quot; y=&quot;454&quot; width=&quot;28&quot; height=&quot;32&quot; colour=&quot;MediumSlateBlue&quot; /&gt;
        ///	&lt;brick x=&quot;83&quot; y=&quot;454&quot; width=&quot;28&quot; height=&quot;32&quot; colour=&quot;MediumSlateBlue&quot; /&gt;
        ///	&lt;brick x=&quot;83&quot; y=&quot;46&quot; width=&quot;28&quot; height=&quot;32&quot; colour=&quot;MediumSlateBlue&quot; /&gt;
        ///	&lt;brick x=&quot;614&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lvl1Fruit {
            get {
                return ResourceManager.GetString("lvl1Fruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bricks&gt;
        ///	&lt;brick type=&quot;error&quot; x=&quot;76&quot; y=&quot;123&quot; width=&quot;38&quot; height=&quot;41&quot; colour=&quot;Pink&quot; /&gt;
        ///	&lt;brick type=&quot;error&quot; x=&quot;114&quot; y=&quot;123&quot; width=&quot;38&quot; height=&quot;41&quot; colour=&quot;Pink&quot; /&gt;
        ///	&lt;brick type=&quot;error&quot; x=&quot;152&quot; y=&quot;123&quot; width=&quot;38&quot; height=&quot;41&quot; colour=&quot;Pink&quot; /&gt;
        ///	&lt;brick type=&quot;error&quot; x=&quot;228&quot; y=&quot;123&quot; width=&quot;38&quot; height=&quot;41&quot; colour=&quot;Pink&quot; /&gt;
        ///	&lt;brick type=&quot;error&quot; x=&quot;266&quot; y=&quot;123&quot; width=&quot;38&quot; height=&quot;41&quot; colour=&quot;Pink&quot; /&gt;
        ///	&lt;brick type=&quot;error&quot; x=&quot;304&quot; y=&quot;123&quot; width=&quot;38&quot; height=&quot;41&quot; colour=&quot;Pink&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lvl2 {
            get {
                return ResourceManager.GetString("lvl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bricks&gt;
        ///	&lt;brick x=&quot;119&quot; y=&quot;167&quot; width=&quot;28&quot; height=&quot;32&quot; colour=&quot;MediumSlateBlue&quot; /&gt;
        ///	&lt;brick x=&quot;272&quot; y=&quot;167&quot; width=&quot;28&quot; height=&quot;32&quot; colour=&quot;MediumSlateBlue&quot; /&gt;
        ///	&lt;brick x=&quot;423&quot; y=&quot;167&quot; width=&quot;28&quot; height=&quot;32&quot; colour=&quot;MediumSlateBlue&quot; /&gt;
        ///	&lt;brick x=&quot;574&quot; y=&quot;167&quot; width=&quot;28&quot; height=&quot;32&quot; colour=&quot;MediumSlateBlue&quot; /&gt;
        ///	&lt;brick x=&quot;119&quot; y=&quot;335&quot; width=&quot;28&quot; height=&quot;32&quot; colour=&quot;MediumSlateBlue&quot; /&gt;
        ///	&lt;brick x=&quot;272&quot; y=&quot;335&quot; width=&quot;28&quot; height=&quot;32&quot; colour=&quot;MediumSlateBlue&quot; /&gt;
        ///	&lt;bric [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lvl2Fruit {
            get {
                return ResourceManager.GetString("lvl2Fruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bricks&gt;
        ///	&lt;brick type=&quot;error&quot; x=&quot;684&quot; y=&quot;369&quot; width=&quot;38&quot; height=&quot;41&quot; colour=&quot;SandyBrown&quot; /&gt;
        ///	&lt;brick type=&quot;error&quot; x=&quot;684&quot; y=&quot;410&quot; width=&quot;38&quot; height=&quot;41&quot; colour=&quot;SandyBrown&quot; /&gt;
        ///	&lt;brick type=&quot;error&quot; x=&quot;684&quot; y=&quot;447&quot; width=&quot;38&quot; height=&quot;41&quot; colour=&quot;SandyBrown&quot; /&gt;
        ///	&lt;brick type=&quot;error&quot; x=&quot;684&quot; y=&quot;328&quot; width=&quot;38&quot; height=&quot;41&quot; colour=&quot;SandyBrown&quot; /&gt;
        ///	&lt;brick type=&quot;error&quot; x=&quot;684&quot; y=&quot;205&quot; width=&quot;38&quot; height=&quot;41&quot; colour=&quot;SandyBrown&quot; /&gt;
        ///	&lt;brick type=&quot;error&quot; x=&quot;684&quot; y=&quot;246&quot; width [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lvl3 {
            get {
                return ResourceManager.GetString("lvl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pinkDown {
            get {
                object obj = ResourceManager.GetObject("pinkDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pinkLeft {
            get {
                object obj = ResourceManager.GetObject("pinkLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pinkRight {
            get {
                object obj = ResourceManager.GetObject("pinkRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pinkUp {
            get {
                object obj = ResourceManager.GetObject("pinkUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap whiteDown {
            get {
                object obj = ResourceManager.GetObject("whiteDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap whiteLeft {
            get {
                object obj = ResourceManager.GetObject("whiteLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap whiteRight {
            get {
                object obj = ResourceManager.GetObject("whiteRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap whiteUp {
            get {
                object obj = ResourceManager.GetObject("whiteUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
